//! Shared delete propagation helper.
//!
//! Every delete entry point (admin DELETE handler, MCP `tool_delete`) must
//! propagate the soft-delete across all retrieval surfaces: Tantivy FTS index
//! and graph edge store. Silent error swallowing historically produced 30-day
//! windows where deleted content stayed in BM25 → reranker (RED-SD-1/-6 from
//! /07-soft-delete-audit). This helper is the single point that enforces
//! storage + tantivy + graph cleanup with propagated errors.

use std::sync::Arc;

use anyhow::{Context, Result};
use loomem_core::graph::GraphStore;
use loomem_core::storage::RocksDbStore;
use loomem_core::tantivy_index::TantivyIndex;
use tokio::sync::Mutex;

use crate::AppState;

/// Per-step outcome of `delete_memory_fully`. Each step is independent and
/// records its own `Result`. The HTTP handler maps overall outcome to
/// 200 (all OK), 207 (partial — at least one step failed), or 404
/// (`store_deleted == false`, chunk did not exist).
///
/// Cycle/117 (delete chain reorder + partial-success): the previous fail-fast
/// chain (store → tantivy → graph → embedding) returned HTTP 500 from any
/// graph deserialize failure and left the embedding in place — embedding
/// leak. Reordered to store → tantivy → embedding → graph so the cheap
/// idempotent steps (store, tantivy, embedding) always run, and the
/// cross-reference-heavy graph step is last + non-fatal.
#[must_use = "DeleteOutcome captures partial-failure state — discarding it silently swallows tantivy/embedding/graph errors (cycle/124)"]
#[derive(Debug)]
pub struct DeleteOutcome {
    /// True iff `store.delete_by_id` reported the chunk existed. Maps to
    /// HTTP 404 when false.
    pub store_deleted: bool,
    /// Always `Ok(())` — fatal store errors are surfaced as `Err` returns
    /// from `delete_memory_fully` (the `?` on `store.delete_by_id`), never
    /// captured here. Retained for API-shape symmetry with the other per-step
    /// fields; the HTTP 207 response body therefore always shows
    /// `"store": "ok"`. Structural removal would change the response shape
    /// — out of scope for /124. (cycle/124 P2 #1, Greptile review on PR #191.)
    pub store: Result<()>,
    pub tantivy: Result<()>,
    pub embedding: Result<()>,
    pub graph: Result<()>,
}

impl DeleteOutcome {
    /// True when every step succeeded. False when at least one step failed.
    pub fn all_ok(&self) -> bool {
        self.store.is_ok() && self.tantivy.is_ok() && self.embedding.is_ok() && self.graph.is_ok()
    }
}

/// Soft-delete a chunk across all retrieval surfaces.
///
/// Calls, in order: `store.delete_by_id` (RocksDB soft-delete),
/// `tantivy.delete_document` (FTS tombstone), `store.delete_embedding`
/// (vector index cleanup), `graph.remove_chunk_references` (edge cleanup).
/// All four ops are idempotent — on partial failure the caller can retry
/// and reach a consistent state.
///
/// Returns `DeleteOutcome` capturing per-step results. The handler decides
/// HTTP status from the outcome (200 / 207 / 404). The function itself
/// only returns `Err` if `store.delete_by_id` (the first step, which
/// determines existence) fails fatally; tantivy/embedding/graph step
/// failures are captured inside the outcome and do NOT short-circuit
/// the chain — this is the cycle/117 fix for the embedding leak.
///
/// Embedding hard-delete rationale (cycle/78 fix): the chunk itself is
/// soft-deleted (sets `deleted_at`, content preserved for the 30-day
/// recovery window); the embedding is hard-deleted because it is a derived
/// index of `chunk.content` and can be regenerated by the embedding queue
/// if the chunk is later recovered.
///
/// Rollback strategy on failure: each step is idempotent; the caller can
/// retry the whole call and the steps that already succeeded will no-op.
pub async fn delete_memory_fully(
    store: &RocksDbStore,
    tantivy: &Mutex<TantivyIndex>,
    graph: &GraphStore,
    id: &str,
) -> Result<DeleteOutcome> {
    let store_deleted = store
        .delete_by_id(id)
        .context("store.delete_by_id failed")?;

    let tantivy_result = {
        let mut idx = tantivy.lock().await;
        idx.delete_document(id)
    };
    if let Err(err) = tantivy_result.as_ref() {
        tracing::error!(
            id = %id,
            error = %err,
            "tantivy.delete_document failed after store.delete_by_id succeeded — orphan detected, retry required"
        );
    }

    let embedding_result = store.delete_embedding(id);
    if let Err(err) = embedding_result.as_ref() {
        tracing::error!(
            id = %id,
            error = %err,
            "store.delete_embedding failed after store + tantivy delete — embedding leak, retry required"
        );
    }

    let graph_result = graph.remove_chunk_references(id);
    if let Err(err) = graph_result.as_ref() {
        tracing::error!(
            id = %id,
            error = %err,
            "graph.remove_chunk_references failed after store + tantivy + embedding delete — edges stale, retry required"
        );
    }

    Ok(DeleteOutcome {
        store_deleted,
        store: Ok(()),
        tantivy: tantivy_result
            .map_err(|e| e.context("tantivy.delete_document failed after store soft-delete")),
        embedding: embedding_result
            .map_err(|e| e.context("store.delete_embedding failed after store + tantivy delete")),
        graph: graph_result.map_err(|e| {
            e.context(
                "graph.remove_chunk_references failed after store + tantivy + embedding delete",
            )
        }),
    })
}

/// Post-retrieval soft-delete guard. Returns true when the chunk is missing,
/// unreadable, or has `deleted_at` set — treats unknown/error states as deleted
/// (fail-closed for privacy, per /07-soft-delete-fix brief Krok 3b).
pub fn is_deleted_in_store(state: &Arc<AppState>, id: &str) -> bool {
    match state.store.get_chunk(id) {
        Ok(Some(chunk)) => chunk.deleted_at.is_some(),
        Ok(None) | Err(_) => true,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use loomem_core::config::{RocksDbConfig, TantivyConfig};
    use loomem_core::storage::Chunk;
    use loomem_core::tantivy_index::TextDocument;
    use std::sync::Arc;
    use tempfile::TempDir;

    fn rocks_config() -> RocksDbConfig {
        RocksDbConfig {
            max_open_files: 100,
            compression: "lz4".to_string(),
            write_buffer_size: 4 * 1024 * 1024,
            max_write_buffer_number: 2,
        }
    }

    fn tantivy_config() -> TantivyConfig {
        TantivyConfig {
            enabled: true,
            heap_size_mb: 50,
            drift_warn_pct: 5.0,
            auto_rebuild_on_drift: false,
        }
    }

    fn make_chunk(id: &str, stream: &str, content: &str) -> Chunk {
        Chunk {
            id: id.to_string(),
            content: content.to_string(),
            stream: stream.to_string(),
            level: 0,
            score: 0.5,
            timestamp: 1_700_000_000,
            consolidated: false,
            dormant: false,
            in_progress: false,
            prompt_version: None,
            source_ids: None,
            last_decay: None,
            metadata: None,
            importance: None,
            persistent: false,
            last_implicit_boost: None,
            access_count: 0,
            source: None,
            created_by: None,
            updated_at: None,
            valid_from: None,
            valid_until: None,
            is_latest: true,
            superseded_by: None,
            supersedes_id: None,
            root_memory_id: None,
            version: 1,
            memory_type: None,
            extraction_meta: None,
            deleted_at: None,
            trust_level: None,
            ingester_user_id: None,

            alpha: 1.0,
            beta: 1.0,
            harmful_count: 0,
            n_ratings: 0,
            last_rated_at: None,
            provenance_role: loomem_core::storage::ProvenanceRole::Claim,
        }
    }

    fn make_text_doc(chunk: &Chunk) -> TextDocument {
        TextDocument {
            id: chunk.id.clone(),
            content: chunk.content.clone(),
            user_id: "u1".to_string(),
            app_id: "app1".to_string(),
            level: chunk.level,
            timestamp: chunk.timestamp as i64,
            stream: chunk.stream.clone(),
            entities: None,
            relations: None,
            event_date: None,
            source_agent: None,
        }
    }

    fn setup() -> (
        TempDir,
        Arc<RocksDbStore>,
        Arc<Mutex<TantivyIndex>>,
        Arc<GraphStore>,
    ) {
        let tmp = TempDir::new().unwrap();
        let store =
            Arc::new(RocksDbStore::open(tmp.path().join("rocks"), &rocks_config()).unwrap());
        let tantivy = Arc::new(Mutex::new(
            TantivyIndex::open(tmp.path().join("tantivy"), &tantivy_config()).unwrap(),
        ));
        let graph = Arc::new(GraphStore::new(store.clone()));
        (tmp, store, tantivy, graph)
    }

    #[tokio::test]
    async fn test_delete_memory_fully_soft_deletes_and_propagates() {
        let (_tmp, store, tantivy, graph) = setup();
        let chunk = make_chunk("test-id-1", "s1", "secret content");
        store.store_chunk(&chunk).unwrap();

        // Index in tantivy so we can observe the delete propagates.
        {
            let mut idx = tantivy.lock().await;
            idx.index_document(make_text_doc(&chunk)).unwrap();
            idx.commit().unwrap();
        }

        assert!(store.get_chunk("test-id-1").unwrap().is_some());

        let outcome = delete_memory_fully(&store, &tantivy, &graph, "test-id-1")
            .await
            .unwrap();
        assert!(
            outcome.store_deleted,
            "expected store_deleted=true for existing chunk"
        );
        assert!(outcome.all_ok(), "expected all steps OK for happy path");

        let after = store.get_chunk("test-id-1").unwrap().unwrap();
        assert!(
            after.deleted_at.is_some(),
            "deleted_at should be set after delete_memory_fully"
        );
    }

    #[tokio::test]
    async fn test_delete_memory_fully_idempotent_on_missing_id() {
        let (_tmp, store, tantivy, graph) = setup();

        let outcome = delete_memory_fully(&store, &tantivy, &graph, "missing-id")
            .await
            .unwrap();
        assert!(
            !outcome.store_deleted,
            "expected store_deleted=false for missing chunk"
        );
        assert!(
            outcome.all_ok(),
            "expected all steps OK (idempotent no-op) for missing"
        );

        let outcome2 = delete_memory_fully(&store, &tantivy, &graph, "missing-id")
            .await
            .unwrap();
        assert!(!outcome2.store_deleted);
    }

    #[tokio::test]
    async fn test_delete_memory_fully_idempotent_retry_after_soft_delete() {
        let (_tmp, store, tantivy, graph) = setup();
        let chunk = make_chunk("test-id-retry", "s1", "retry content");
        store.store_chunk(&chunk).unwrap();

        let first = delete_memory_fully(&store, &tantivy, &graph, "test-id-retry")
            .await
            .unwrap();
        assert!(
            first.all_ok(),
            "setup (first) delete must succeed for retry-idempotency test to be meaningful"
        );

        let retry = delete_memory_fully(&store, &tantivy, &graph, "test-id-retry")
            .await
            .unwrap();
        assert!(
            retry.store_deleted,
            "retry must remain idempotent and report store_deleted=true"
        );
    }

    /// Cycle/78 regression: memory_delete must remove the embedding from
    /// CF_EMBEDDINGS, not just tombstone the chunk. Pre-fix, soft-delete left
    /// the embedding in place until the ~30-day hard-purge window — which:
    /// 1. Inflated `count_embeddings()` (the global metric in memory_status)
    ///    so it never decreased after delete.
    /// 2. Polluted `vector_search`'s candidate pool (zombie embeddings got
    ///    cosine-scored alongside live ones, then dropped post-rank by the
    ///    is_deleted_in_store filter — wasting top_k slots).
    /// 3. Polluted clustering centroids (clustering loops over
    ///    `get_all_embeddings()` and only filtered by stream + is_latest,
    ///    not by deleted_at — so centroids drifted toward deleted content).
    #[tokio::test]
    async fn test_delete_memory_fully_removes_embedding_from_index() {
        let (_tmp, store, tantivy, graph) = setup();
        let chunk = make_chunk("test-id-emb", "s1", "embedding leak repro");
        store.store_chunk(&chunk).unwrap();
        store
            .store_embedding("test-id-emb", vec![0.1f32, 0.2, 0.3])
            .expect("store_embedding");

        // Pre-condition: embedding present, count == 1.
        assert_eq!(store.count_embeddings().unwrap(), 1);
        assert!(store.get_embedding("test-id-emb").unwrap().is_some());

        let outcome = delete_memory_fully(&store, &tantivy, &graph, "test-id-emb")
            .await
            .unwrap();
        assert!(
            outcome.all_ok(),
            "delete_memory_fully should report all_ok in the embedding-leak repro: {outcome:?}"
        );

        // Post-condition: embedding removed, count == 0.
        assert_eq!(
            store.count_embeddings().unwrap(),
            0,
            "embedding count must drop to 0 after memory_delete (cycle/78 leak repro)"
        );
        assert!(
            store.get_embedding("test-id-emb").unwrap().is_none(),
            "embedding must be hard-deleted from CF_EMBEDDINGS"
        );

        // Chunk is soft-deleted (content preserved for recovery), but
        // embedding is recomputable from content if needed.
        let chunk_after = store.get_chunk("test-id-emb").unwrap().unwrap();
        assert!(chunk_after.deleted_at.is_some());
        assert_eq!(chunk_after.content, "embedding leak repro");
    }

    /// Cycle/117 (a): partial-success when graph step fails. Corrupt the
    /// `graph:chunk:<id>` reverse-index bytes so `remove_chunk_references`
    /// returns Err from `get_entities_for_chunk` deserialize. The chain must
    /// still soft-delete the chunk and hard-delete the embedding (i.e. no
    /// leak), with the failure surfaced in `outcome.graph`.
    #[tokio::test]
    async fn test_delete_partial_success_graph_fails() {
        let (_tmp, store, tantivy, graph) = setup();
        let chunk = make_chunk("test-id-partial", "s1", "partial success body");
        store.store_chunk(&chunk).unwrap();
        store
            .store_embedding("test-id-partial", vec![0.1f32, 0.2, 0.3])
            .expect("store_embedding");

        // Poison the graph chunk reverse-index with malformed JSON. This
        // bypasses fail-graceful (which only covers entity reads) and forces
        // remove_chunk_references → get_entities_for_chunk to return Err.
        store
            .put(b"graph:chunk:test-id-partial", b"\xff\xfe not valid json")
            .expect("put corrupted chunk index");

        let outcome = delete_memory_fully(&store, &tantivy, &graph, "test-id-partial")
            .await
            .expect("delete_memory_fully should return outcome, not Err");

        // Store + tantivy + embedding succeeded; graph step is the failure.
        assert!(outcome.store_deleted, "chunk existed → store_deleted=true");
        assert!(outcome.store.is_ok(), "store step OK");
        assert!(outcome.tantivy.is_ok(), "tantivy step OK");
        assert!(outcome.embedding.is_ok(), "embedding step OK (no leak)");
        assert!(
            outcome.graph.is_err(),
            "graph step must fail on corrupted chunk reverse-index"
        );
        assert!(
            !outcome.all_ok(),
            "all_ok() must be false when graph step failed"
        );

        // Critical post-condition: embedding is GONE despite graph failure.
        // Pre-fix (fail-fast), the embedding would remain because the chain
        // short-circuited at graph. This is the cycle/117 embedding-leak fix.
        assert!(
            store.get_embedding("test-id-partial").unwrap().is_none(),
            "embedding must be hard-deleted even when graph step failed"
        );
        assert_eq!(store.count_embeddings().unwrap(), 0);

        // Chunk is still soft-deleted.
        let chunk_after = store.get_chunk("test-id-partial").unwrap().unwrap();
        assert!(chunk_after.deleted_at.is_some());
    }

    /// Cycle/117 (b): happy path returns DeleteOutcome with all steps OK.
    #[tokio::test]
    async fn test_delete_full_success() {
        let (_tmp, store, tantivy, graph) = setup();
        let chunk = make_chunk("test-id-full", "s1", "full success body");
        store.store_chunk(&chunk).unwrap();
        store
            .store_embedding("test-id-full", vec![0.1f32, 0.2, 0.3])
            .expect("store_embedding");

        let outcome = delete_memory_fully(&store, &tantivy, &graph, "test-id-full")
            .await
            .expect("delete_memory_fully should succeed");

        assert!(outcome.store_deleted, "store_deleted=true for existing");
        assert!(outcome.all_ok(), "happy path → all steps OK → HTTP 200");
        assert!(store.get_embedding("test-id-full").unwrap().is_none());
    }

    /// Cycle/117 (c): missing chunk → store_deleted=false → HTTP 404
    /// (handler maps), never HTTP 500. The chain still runs idempotently.
    #[tokio::test]
    async fn test_delete_missing_chunk() {
        let (_tmp, store, tantivy, graph) = setup();

        let outcome = delete_memory_fully(&store, &tantivy, &graph, "never-existed")
            .await
            .expect("delete_memory_fully should succeed on missing id");

        assert!(
            !outcome.store_deleted,
            "missing chunk → store_deleted=false → handler returns 404"
        );
        assert!(
            outcome.all_ok(),
            "all downstream steps no-op on missing id, must not error"
        );
    }

    #[test]
    fn test_deleted_at_semantics_match_is_deleted_contract() {
        // is_deleted_in_store requires an AppState which is heavy to build
        // in-test. Exercise the store pathway directly to assert the
        // fail-closed contract captured by is_deleted_in_store.
        let tmp = TempDir::new().unwrap();
        let store = RocksDbStore::open(tmp.path().join("rocks"), &rocks_config()).unwrap();

        // Missing id → Ok(None) → treated as deleted.
        assert!(matches!(store.get_chunk("never-inserted"), Ok(None)));

        // Present, not deleted → deleted_at is None.
        let chunk = make_chunk("present", "s1", "hello");
        store.store_chunk(&chunk).unwrap();
        let got = store.get_chunk("present").unwrap().unwrap();
        assert!(got.deleted_at.is_none());

        // Soft-deleted → deleted_at is Some.
        store.delete_by_id("present").unwrap();
        let got2 = store.get_chunk("present").unwrap().unwrap();
        assert!(got2.deleted_at.is_some());
    }
}
